const countries = {
  BD: "Bangladesh",
  BE: "Belgium",
  BG: "Bulgaria",
  BA: "Bosnia and Herzegovina",
  JM: "Jamaica",
  BR: "Brazil",
  BY: "Belarus",
  RU: "Russia",
  RS: "Serbia",
  TM: "Turkmenistan",
  TJ: "Tajikistan",
  RO: "Romania",
  GR: "Greece",
  JP: "Japan",
  GE: "Georgia",
  GB: "United Kingdom",
  GI: "Gibraltar",
  OM: "Oman",
  TN: "Tunisia",
  JO: "Jordan",
  HR: "Croatia",
  HU: "Hungary",
  HK: "Hong Kong",
  VE: "Venezuela",
  PS: "Palestinian Territory",
  PT: "Portugal",
  IQ: "Iraq",
  PA: "Panama",
  PE: "Peru",
  PK: "Pakistan",
  PL: "Poland",
  EE: "Estonia",
  EG: "Egypt",
  ZA: "South Africa",
  EC: "Ecuador",
  IT: "Italy",
  VN: "Vietnam",
  ET: "Ethiopia",
  ZW: "Zimbabwe",
  SA: "Saudi Arabia",
  ES: "Spain",
  ME: "Montenegro",
  MD: "Moldova",
  MA: "Morocco",
  MC: "Monaco",
  UZ: "Uzbekistan",
  MN: "Mongolia",
  MK: "Macedonia",
  MT: "Malta",
  TZ: "Tanzania",
  MY: "Malaysia",
  MX: "Mexico",
  IL: "Israel",
  FR: "France",
  FI: "Finland",
  NL: "Netherlands",
  NO: "Norway",
  NG: "Nigeria",
  NZ: "New Zealand",
  CH: "Switzerland",
  CO: "Colombia",
  CN: "China",
  CL: "Chile",
  CA: "Canada",
  CG: "Republic of the Congo",
  CZ: "Czech Republic",
  CY: "Cyprus",
  CR: "Costa Rica",
  CU: "Cuba",
  SY: "Syria",
  KG: "Kyrgyzstan",
  KE: "Kenya",
  KH: "Cambodia",
  SK: "Slovakia",
  KR: "South Korea",
  SI: "Slovenia",
  KP: "North Korea",
  KW: "Kuwait",
  SN: "Senegal",
  SM: "San Marino",
  KZ: "Kazakhstan",
  SG: "Singapore",
  SE: "Sweden",
  DK: "Denmark",
  DE: "Germany",
  YE: "Yemen",
  DZ: "Algeria",
  US: "United States",
  UY: "Uruguay",
  LA: "Laos",
  TW: "Taiwan",
  TR: "Turkey",
  LI: "Liechtenstein",
  LV: "Latvia",
  LT: "Lithuania",
  LU: "Luxembourg",
  TH: "Thailand",
  LY: "Libya",
  AE: "United Arab Emirates",
  AD: "Andorra",
  AF: "Afghanistan",
  IS: "Iceland",
  IR: "Iran",
  AM: "Armenia",
  AL: "Albania",
  AO: "Angola",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  IN: "India",
  AZ: "Azerbaijan",
  IE: "Ireland",
  ID: "Indonesia",
  UA: "Ukraine",
  QA: "Qatar",
};

const iso2 = (country) => {
  const idOfCountry = Object.values(countries).findIndex((c) => c === country);
  return Object.keys(countries)[idOfCountry];
};

export default countries;
export { iso2 };
